load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

# This is a fake repository - `override-repository` handles this in practice
git_repository(
    name = "rules_pods",
    remote = "https://github.com/pinterest/PodToBUILD.git",
    branch = "master",
)

# In real usage, point rules_pods at a release.
#http_archive(
#    name = "rules_pods",
#    urls = ["https://github.com/Pinterst/PodToBUILD/releases/__RELEASE__.zip"],
#)

git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    tag = "0.16.1",
)

load(
    "@build_bazel_rules_apple//apple:repositories.bzl",
    "apple_rules_dependencies",
)

apple_rules_dependencies()

load(
    "@build_bazel_rules_swift//swift:repositories.bzl",
    "swift_rules_dependencies",
)

swift_rules_dependencies()

load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()

load("@rules_pods//BazelExtensions:workspace.bzl", "new_pod_repository")

new_pod_repository(
    name = "SlackTextViewController",
    url = "https://github.com/slackhq/SlackTextViewController/archive/v1.9.6.zip",
    inhibit_warnings = True
)

