objc_library(name="all", deps=[
    "//Vendor/React:Core",
    "//Vendor/React:CxxBridge",
    "//Vendor/React:DevSupport",
    "//Vendor/React:RCTImage",
    "//Vendor/React:RCTNetwork",
    "//Vendor/React:RCTText",
    "//Vendor/React:RCTWebSocket",
    "//Vendor/React:RCTAnimation"])
