# Process bundles created by PodSpecToBUILD
# Move a bundle of the convention in Pods
# PackageName_Bundle_BundleName
# @see process_ipa.py
py_binary(
    name = "ipa_process",
    main = "process_ipa.py",
    srcs = ["process_ipa.py"],
    visibility = ["//visibility:public"]
)

